#ifndef _VERSION_H_
#define _VERSION_H_

#define CREATE_MAJOR_VERSION "2014_03_08"
#define CREATE_MINOR_VERSION "22_1"
#define CREATE_MINICALC_VERSION CREATE_MAJOR_VERSION ## "_" ## CREATE_MINOR_VERSION

#define MAJOR_VERSION "2014_03_09"
#define MINOR_VERSION "10_1"
#define MINICALC_VERSION MAJOR_VERSION ## "_" ## MINOR_VERSION

#endif //_VERSION_H_